### ISSUE TITLE
Doesn’t cross-compile for Nerves

### ISSUE THREAD

**Issue by TattdCodeMonkey** [TattdCodeMonkey/crc#22]
Since the NIFs are load via erlang files and not elixir now, they are being auto loaded. This breaks cross compiling the module for a nerves project.

**Comment by potatosalad** [comment]
@TattdCodeMonkey I put the wrong cross-compiler variable check in in the `Makefile`.

Instead of this: https://github.com/TattdCodeMonkey/crc/blob/2415b508c9f2ac70496804c24755e2c87ec14611/c_src/Makefile#L91-L93

It should look like this: https://github.com/potatosalad/erlang-serial_framing_protocol/blob/90e9f6079fabc1f182f325f728802e2cfe95842a/c_src/Makefile#L91-L93

I *think* that's the only change that would need to happen to get nerves working again, but I can verify it later tonight.

**Comment by TattdCodeMonkey** [comment]
@potatosalad thanks, I’ll try that out!!

**Comment by potatosalad** [comment]
@TattdCodeMonkey Yeah, I don't think (last time I checked) that this is documented anywhere inside nerves.  I found out through trial and error and/or looking at what other Nerves NIF related projects were doing.

**Comment by fhunleth** [comment]
Nerves overrides `$CC` as well, so this is ok. We take the "belt and suspenders" approach to Make environment variables to try to get most libraries to work without change, but certainly anyone manually crosscompiling will appreciate this.

**Comment by TattdCodeMonkey** [comment]
Resolved by #23
